[package]
name = "auth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

tide = "0.16.0"
openidconnect = "2.2.0"
once_cell = "1.9.0"
serde = "1.0.136"
tracing = "0.1.31"
thiserror = "1.0.30"